### ISSUE TITLE
Multiple packages found with the same name

### ISSUE THREAD

**Issue by shiqizhang6** [utexas-bwi/segbot#50] opened 2015-07-30 17:39 UTC
Multiple packages found with the same name "segbot_gazebo":
- segbot/segbot_gazebo
- segbot_simulator/segbot_gazebo

Multiple packages found with the same name "segbot_gui":
- segbot/segbot_gui
- segbot_apps/segbot_gui

Multiple packages found with the same name "segbot_logical_translator":
- segbot/segbot_logical_translator
- segbot_apps/segbot_logical_translator

Multiple packages found with the same name "segbot_navigation":
- segbot/segbot_navigation
- segbot_apps/segbot_navigation

Multiple packages found with the same name "segbot_simulation_apps":
- segbot/segbot_simulation_apps
- segbot_simulator/segbot_simulation_apps

**Comment by shiqizhang6** [comment] 2015-07-30 17:47
This error appears while running: bwi_launch/launch/simulation.launch
@piyushk

**Comment by piyushk** [comment] 2015-07-30 17:48
@shiqizhang6 We've merged a few repositories. Please run the following commands:
```
cd ~/catkin_ws/src
wstool rm segbot_apps segbot_simulator
rm -rf segbot_apps segbot_simulator
cd ~/catkin_ws
catkin_make clean
catkin_make
```

**Comment by jack-oquin** [comment] 2015-07-30 17:48
This is caused by us merging **segbot_simulator** and **segbot_apps** into **segbot**.

When you update your workspace, you need to delete the two other repositories.

**Comment by jack-oquin** [comment] 2015-07-30 17:49
We should send a warning note to the bwi mailing list.

**Comment by piyushk** [comment] 2015-07-30 17:50
Already done :+1:.

**Closed by piyushk** 2015-07-30 17:50 UTC
